@startuml Diagnostic Integrations - Class Diagram

title "Integrations - Class Diagram"


package Framework <<Frame>> {
    class FrameworkDataItem
}
class Integration {
}
class DiagnosticIntegration {
}
package StandardDiagnostic <<Frame>>{
    class StandardDiagnostic {  
    }
}
package StandardPacs <<Frame>> {
    class StandardPacs {
    }
}
class IdexxReferenceShared {
}
class IdexxVetConnectPlus {
}
class IdexxVetConnectPlusInternal {
}
class IdexxReferenceUS {
}
interface HasLegacyIntegrationInterface {
}
package PacsIntegration <<Frame>> {
    class PacsIntegration {
    }
}
class AbaxisVetscanFuse {
}
class Antech {
}
class LabTransmit{
}
class EmailedLabs{
}
class IdexxIvls{
}
class Asteris{
}
class VetRocket{
}
class Cuattro{
}

FrameworkDataItem <|-- Integration

Integration <|-- DiagnosticIntegration
Integration <|-- StandardPacs

DiagnosticIntegration <|-- IdexxReferenceShared
DiagnosticIntegration <|-- IdexxIvls
DiagnosticIntegration <|-- StandardDiagnostic
DiagnosticIntegration <|-- PacsIntegration
DiagnosticIntegration <|-- AbaxisVetscanFuse
DiagnosticIntegration <|-- Antech
DiagnosticIntegration <|-- LabTransmit
DiagnosticIntegration <|-- EmailedLabs

IdexxReferenceShared <|-- IdexxVetConnectPlus
IdexxReferenceShared <|-- IdexxVetConnectPlusInternal
IdexxReferenceShared <|-- IdexxReferenceUS

'HasLegacyIntegrationInterface <|.. IdexxVetConnectPlus
'HasLegacyIntegrationInterface <|.. IdexxVetConnectPlusInternal


note left of IdexxReferenceShared
    File is <b>3400</b> lines, with <b>109</b> functions.
    No defined responsibilities other than "common methods".
    No idea what functions are still being used.
    Functions in there called Temp, but still sitting there for years.
    Unsafe calls to functions that are not on all children.
endnote

note bottom of IdexxReferenceUS
    File 2500 lines, with 94 functions.
    A lot of the functions are to do with the Migration.
    How many of these functions are still in use
endnote


@enduml